apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mint

resources:
  - namespace.yaml
  - secrets.yaml
  - mysql.yaml
  - mint-server.yaml
  - ingressroute-mint-api.yaml

commonLabels:
  app.kubernetes.io/part-of: mint-server
  app.kubernetes.io/managed-by: kustomize
